### ISSUE TITLE
What does it mean to copy from META.json to Makefile.PL?

### ISSUE THREAD

**Issue by mauke** [Perl-Toolchain-Gang/cpan-static#10]
The *EXTERNAL REQUIREMENTS* section states:

> [...] a valid `Build.PL` (per CPAN::API::BuildPL) or `Makefile.PL` **must** be present as a fallback. It **may** be copied verbatim to from `META.json`. The same may be done for `MYMETA.yml`/`META.yml`.

So a cpan client may copy `META.json` verbatim to `Makefile.PL`, and copy `MYMETA.yml` verbatim to `Makefile.PL`, and copy `META.yml` verbatim to `Makefile.PL`.

This makes no sense.

**Comment by miyagawa** [comment]
This seems to be a copy-paste failure and maybe supposed to be put in the Configuration section later. "It" refers to `MYMETA.json` i.e. a CPAN client can choose to take META.json and generate MYMETA.json verbatim by simply copying it.

**Comment by Leont** [comment]
Yeah that ended up in the wrong place, moved it so that it now makes sense.

**Comment by mauke** [comment]
Fixed in https://github.com/Perl-Toolchain-Gang/cpan-static/commit/f9055db1b9e253c883748f20921583e08089fe2f.
