### ISSUE TITLE
How does a distribution opt in to static installation?

### ISSUE THREAD

**Issue by mauke** [Perl-Toolchain-Gang/cpan-static#12]
The spec talks mostly about what cpan clients should do to install distributions statically, but how do I as an author specify that my distribution supports static installation?

**Comment by Leont** [comment]
This is essentially a duplicate of #6

**Comment by mauke** [comment]
Fixed in https://github.com/Perl-Toolchain-Gang/cpan-static/commit/478aa5d9ab71f8c6578d888773b412e287e0e37c.
